.\"
.Dd "Sep 08, 2004"
.Dt ILCMD 8
.Os "Uppsala Universitet"
.Sh NAME
.Nm ilcmd
.Nd general-purpose command-line client for iplogin2
.Sh SYNOPSIS
.Nm ilcmd
.Ar conffile
.Ar clientname
.Ar command
.Sh DESCRIPTION
.Nm ilcmd
is a simple command line interface to 
.Nm iplogin2
allowing the operator to executing
.Nm iplogin2
commands from a script or from the command line.
.Pp
.Nm ilcmd
uses a 
.Ar conffile
to find out which server to connect to and other
parameters. The
.Ar clientname
is used to find the correct configuration inside
this configuration file.
.Pp
.Bl -tag -width flag
.It Ar conffile
is the configuration file to use.
.It Ar clientname
is the name of the client definition to use in
.Ar conffile
.It Ar command
is the command to execute - this must be quoted when used in a shell or shell script.
.El
.Sh SECRET KNOWLEDGE
.Nm ilcmd
actually has compiled-in default values for 
.Ar conffile
and
.Ar clientname.
The
.Ar conffile,
when given as ".", will default to either one of two compiled-in
values. The
.Ar clientname,
when given as ".", will default to "localhost".
.Sh BUGS
The command-line syntax should be more flexible.
.Sh SEE ALSO
.Xr iplogin2 8 ,
.Xr iladmin 8 ,
.Xr ilcount 8 ,
.Xr iplogin2-conffile 5
