#ILADMIN_DEFS=-DCONFFILE=\"/usr/local/etc/iplogin.conf\" -DCLIENTNAME=\"localhost\"
ILADMIN_DEFS=-DCONFFILE=\"/opt/iplogin2/etc/iplogin2.conf\" -DCLIENTNAME=\"localhost\"

CC= gcc
OPT= -O -Wall # -g
DEFS=-DNO_SHARED_LIBS=1 -DLINUX # -DFOO # -DBIGTRACE # -DDEBUG #-DSTATS
LIBS=-lcrypto -lwrap -ldl

ACC_OPT=-fPIC -O -Wall -shared

IPTSRCDIR=./iptables
IPTINCDIR=$(IPTSRCDIR)/include

CFLAGS = $(OPT) $(DEFS) -I$(IPTINCDIR)

IPTLIBDIR=/usr/lib/iptables
IPTLDLIB=$(IPTSRCDIR)/libiptc/libiptc.a $(IPTSRCDIR)/extensions/libext.a
IPTFLAGS=-I$(IPTINCDIR) -DIPT_LIB_DIR=\"$(IPTLIBDIR)\" -rdynamic
IPT=$(IPTFLAGS) $(IPTLDLIB)

OBJ=main.o engine.o find_interface.o misc.o filterchains.o filterchains2.o commands.o icmpping.o arpping.o config.o 
ILGLUE_OBJ=ilglue.o misc.o
ILGLUE_LIB=libilglue.a
ILGLUE_XOBJ=varlist.o hlcrypt.o conffile.o
LIBOBJ=usernode.o varlist.o hlcrypt.o conffile.o trace.o mymalloc.o accounting.o
PROGS=iplogin2 ilcmd iladmin iladmin_random find_interface testipt ilcount

SRCS=main.c engine.c find_interface.c misc.c filterchains.c \
	filterchains2.c commands.c icmpping.c arpping.c config.c \
	ilglue.c misc.c usernode.c varlist.c hlcrypt.c conffile.c \
	trace.c mymalloc.c

all: $(PROGS) libilglue.a acclib_test.so

clean:
	rm -f $(PROGS) *.o libilglue.a acclib_test.so *~ core

rclean:
	rm -f $(PROGS) *.o libilglue.a acclib_test.so *~ core
	(cd $(IPTSRCDIR); make distclean)

iplogin2: $(OBJ) $(LIBOBJ) $(IPTSRCDIR)/libiptc/libiptc.a
	$(CC) --static -Os $(CFLAGS) $(INCDIR) -o iplogin2 $(OBJ) $(LIBOBJ) $(IPT) $(LDFLAGS) $(LIBS)
	strip iplogin2

$(IPTSRCDIR)/libiptc/libiptc.a:
	(cd $(IPTSRCDIR); make BINDIR=/usr/sbin LIBDIR=/usr/lib MANDIR=/usr/man NO_SHARED_LIBS=1)

iladmin: iladmin.c $(LIBOBJ) $(ILGLUE_OBJ)
	$(CC) $(CFLAGS) $(ILADMIN_DEFS) $(INCDIR) -o iladmin iladmin.c $(LIBOBJ) $(ILGLUE_OBJ) $(LDFLAGS) $(LIBS)

ilcount: ilcount.c $(LIBOBJ) $(ILGLUE_OBJ)
	$(CC) $(CFLAGS) $(INCDIR) -o ilcount ilcount.c $(LIBOBJ) $(ILGLUE_OBJ) $(LDFLAGS) $(LIBS)

ilcmd: ilcmd.c $(LIBOBJ)
	$(CC) $(CFLAGS) $(INCDIR) -o ilcmd ilcmd.c $(LIBOBJ) $(LDFLAGS) $(LIBS)

iladmin_random: iladmin_random.c $(LIBOBJ)
	$(CC) $(CFLAGS) $(INCDIR) -o iladmin_random iladmin_random.c $(LIBOBJ) $(LDFLAGS) $(LIBS)

find_interface: find_interface.c
	$(CC) $(CFLAGS) $(INCDIR) -DTEST_NETLINK -o find_interface find_interface.c

libilglue.a:    $(ILGLUE_OBJ) $(ILGLUE_XOBJ)
	ar -r $(ILGLUE_LIB) $(ILGLUE_OBJ) $(ILGLUE_XOBJ)
	ranlib $(ILGLUE_LIB)

acclib_test.so:	acclib_test.o
	${CC} ${ACC_OPT} acclib_test.o -o acclib_test.so

testipt: testipt.c $(LIBOBJ) filterchains2.o
	$(CC) $(CFLAGS) $(INCDIR) -o testipt testipt.c filterchains2.o $(LIBOBJ) $(IPT) $(LDFLAGS) $(LIBS)

install: iplogin2
	cat INSTALL

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

# DO NOT DELETE

main.o: /usr/include/stdio.h /usr/include/features.h /usr/include/sys/cdefs.h
main.o: /usr/include/gnu/stubs.h
main.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
main.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
main.o: /usr/include/bits/sched.h /usr/include/libio.h
main.o: /usr/include/_G_config.h /usr/include/wchar.h
main.o: /usr/include/bits/wchar.h /usr/include/gconv.h
main.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
main.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
main.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
main.o: /usr/include/bits/endian.h /usr/include/sys/select.h
main.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
main.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
main.o: /usr/include/alloca.h /usr/include/string.h /usr/include/syslog.h
main.o: /usr/include/sys/syslog.h conffile.h varlist.h usernode.h
main.o: /usr/include/netinet/in.h /usr/include/stdint.h
main.o: /usr/include/bits/wordsize.h /usr/include/bits/socket.h
main.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
main.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
main.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
main.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
main.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
main.o: /usr/include/linux/if_arp.h /usr/include/linux/netdevice.h
main.o: /usr/include/linux/if.h /usr/include/linux/types.h
main.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
main.o: /usr/include/asm/posix_types.h /usr/include/asm/types.h
main.o: /usr/include/linux/socket.h /usr/include/linux/if_ether.h
main.o: /usr/include/linux/if_packet.h /usr/include/asm/atomic.h
main.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
main.o: /usr/include/asm/cache.h /usr/include/asm/byteorder.h
main.o: /usr/include/linux/byteorder/little_endian.h
main.o: /usr/include/linux/byteorder/swab.h
main.o: /usr/include/linux/byteorder/generic.h engine.h config.h
main.o: /usr/include/signal.h /usr/include/bits/signum.h
main.o: /usr/include/bits/siginfo.h /usr/include/bits/sigaction.h
main.o: /usr/include/bits/sigcontext.h /usr/include/asm/sigcontext.h
main.o: /usr/include/bits/sigstack.h /usr/include/bits/sigthread.h
main.o: /usr/include/arpa/inet.h /usr/include/unistd.h
main.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
main.o: /usr/include/getopt.h /usr/include/pwd.h /usr/include/sys/socket.h
main.o: /usr/include/sys/uio.h /usr/include/bits/uio.h /usr/include/netdb.h
main.o: /usr/include/rpc/netdb.h /usr/include/bits/netdb.h trace.h
main.o: accounting.h
engine.o: /usr/include/tcpd.h /usr/include/sys/time.h /usr/include/features.h
engine.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
engine.o: /usr/include/bits/types.h
engine.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
engine.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
engine.o: /usr/include/time.h /usr/include/bits/time.h
engine.o: /usr/include/sys/select.h /usr/include/bits/select.h
engine.o: /usr/include/bits/sigset.h /usr/include/sys/timeb.h
engine.o: /usr/include/string.h /usr/include/stdlib.h
engine.o: /usr/include/sys/types.h /usr/include/endian.h
engine.o: /usr/include/bits/endian.h /usr/include/sys/sysmacros.h
engine.o: /usr/include/alloca.h /usr/include/signal.h
engine.o: /usr/include/bits/signum.h /usr/include/bits/siginfo.h
engine.o: /usr/include/bits/wordsize.h /usr/include/bits/sigaction.h
engine.o: /usr/include/bits/sigcontext.h /usr/include/asm/sigcontext.h
engine.o: /usr/include/bits/sigstack.h /usr/include/bits/sigthread.h
engine.o: /usr/include/syslog.h /usr/include/sys/syslog.h
engine.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
engine.o: /usr/include/errno.h /usr/include/bits/errno.h
engine.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
engine.o: /usr/include/arpa/inet.h /usr/include/netinet/in.h
engine.o: /usr/include/stdint.h /usr/include/bits/wchar.h
engine.o: /usr/include/bits/socket.h /usr/include/limits.h
engine.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
engine.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
engine.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
engine.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
engine.o: /usr/include/bits/byteswap.h /usr/include/sys/socket.h
engine.o: /usr/include/sys/uio.h /usr/include/bits/uio.h
engine.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
engine.o: /usr/include/bits/confname.h /usr/include/getopt.h
engine.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
engine.o: /usr/include/wchar.h /usr/include/gconv.h
engine.o: /usr/include/bits/stdio_lim.h /usr/include/sys/ioctl.h
engine.o: /usr/include/bits/ioctls.h /usr/include/asm/ioctls.h
engine.o: /usr/include/asm/ioctl.h /usr/include/bits/ioctl-types.h
engine.o: /usr/include/sys/ttydefaults.h socketnode.h hlcrypt.h
engine.o: /usr/include/openssl/sha.h /usr/include/crypt.h varlist.h
engine.o: conffile.h commands.h usernode.h /usr/include/linux/if_arp.h
engine.o: /usr/include/linux/netdevice.h /usr/include/linux/if.h
engine.o: /usr/include/linux/types.h /usr/include/linux/posix_types.h
engine.o: /usr/include/linux/stddef.h /usr/include/asm/posix_types.h
engine.o: /usr/include/asm/types.h /usr/include/linux/socket.h
engine.o: /usr/include/linux/if_ether.h /usr/include/linux/if_packet.h
engine.o: /usr/include/asm/atomic.h /usr/include/linux/config.h
engine.o: /usr/include/linux/autoconf.h /usr/include/asm/cache.h
engine.o: /usr/include/asm/byteorder.h
engine.o: /usr/include/linux/byteorder/little_endian.h
engine.o: /usr/include/linux/byteorder/swab.h
engine.o: /usr/include/linux/byteorder/generic.h filterchains.h arpping.h
engine.o: /usr/include/linux/sockios.h icmpping.h mymalloc.h accounting.h
engine.o: misc.h config.h engine.h trace.h
find_interface.o: /usr/include/stdio.h /usr/include/features.h
find_interface.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
find_interface.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
find_interface.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
find_interface.o: /usr/include/bits/sched.h /usr/include/libio.h
find_interface.o: /usr/include/_G_config.h /usr/include/wchar.h
find_interface.o: /usr/include/bits/wchar.h /usr/include/gconv.h
find_interface.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
find_interface.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
find_interface.o: /usr/include/sys/types.h /usr/include/time.h
find_interface.o: /usr/include/endian.h /usr/include/bits/endian.h
find_interface.o: /usr/include/sys/select.h /usr/include/bits/select.h
find_interface.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
find_interface.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
find_interface.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
find_interface.o: /usr/include/bits/confname.h /usr/include/getopt.h
find_interface.o: /usr/include/string.h /usr/include/netinet/in.h
find_interface.o: /usr/include/stdint.h /usr/include/bits/wordsize.h
find_interface.o: /usr/include/bits/socket.h /usr/include/limits.h
find_interface.o: /usr/include/bits/posix1_lim.h
find_interface.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
find_interface.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
find_interface.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
find_interface.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
find_interface.o: /usr/include/asm/types.h /usr/include/linux/netlink.h
find_interface.o: /usr/include/linux/rtnetlink.h /usr/include/sys/socket.h
find_interface.o: /usr/include/sys/uio.h /usr/include/bits/uio.h
find_interface.o: /usr/include/arpa/inet.h /usr/include/errno.h
find_interface.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
find_interface.o: /usr/include/asm/errno.h /usr/include/netdb.h
find_interface.o: /usr/include/rpc/netdb.h /usr/include/bits/netdb.h
find_interface.o: /usr/include/syslog.h /usr/include/sys/syslog.h
find_interface.o: /usr/include/sys/ioctl.h /usr/include/bits/ioctls.h
find_interface.o: /usr/include/asm/ioctls.h /usr/include/asm/ioctl.h
find_interface.o: /usr/include/bits/ioctl-types.h
find_interface.o: /usr/include/sys/ttydefaults.h usernode.h
find_interface.o: /usr/include/linux/if_arp.h /usr/include/linux/netdevice.h
find_interface.o: /usr/include/linux/if.h /usr/include/linux/types.h
find_interface.o: /usr/include/linux/posix_types.h
find_interface.o: /usr/include/linux/stddef.h /usr/include/asm/posix_types.h
find_interface.o: /usr/include/linux/socket.h /usr/include/linux/if_ether.h
find_interface.o: /usr/include/linux/if_packet.h /usr/include/asm/atomic.h
find_interface.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
find_interface.o: /usr/include/asm/cache.h /usr/include/asm/byteorder.h
find_interface.o: /usr/include/linux/byteorder/little_endian.h
find_interface.o: /usr/include/linux/byteorder/swab.h
find_interface.o: /usr/include/linux/byteorder/generic.h varlist.h
misc.o: /usr/include/stdlib.h /usr/include/features.h
misc.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
misc.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
misc.o: /usr/include/sys/types.h /usr/include/bits/types.h
misc.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
misc.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
misc.o: /usr/include/sys/select.h /usr/include/bits/select.h
misc.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
misc.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
misc.o: /usr/include/arpa/inet.h /usr/include/netinet/in.h
misc.o: /usr/include/stdint.h /usr/include/bits/wchar.h
misc.o: /usr/include/bits/wordsize.h /usr/include/bits/socket.h
misc.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
misc.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
misc.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
misc.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
misc.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
misc.o: /usr/include/sys/wait.h /usr/include/signal.h
misc.o: /usr/include/bits/signum.h /usr/include/bits/siginfo.h
misc.o: /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h
misc.o: /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h
misc.o: /usr/include/bits/sigthread.h /usr/include/sys/resource.h
misc.o: /usr/include/bits/resource.h /usr/include/bits/waitflags.h
misc.o: /usr/include/bits/waitstatus.h /usr/include/sys/socket.h
misc.o: /usr/include/sys/uio.h /usr/include/bits/uio.h /usr/include/unistd.h
misc.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
misc.o: /usr/include/getopt.h /usr/include/netdb.h /usr/include/rpc/netdb.h
misc.o: /usr/include/bits/netdb.h /usr/include/stdio.h /usr/include/libio.h
misc.o: /usr/include/_G_config.h /usr/include/wchar.h /usr/include/gconv.h
misc.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
misc.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
misc.o: /usr/include/syslog.h /usr/include/sys/syslog.h config.h
filterchains.o: /usr/include/string.h /usr/include/features.h
filterchains.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
filterchains.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
filterchains.o: /usr/include/stdio.h /usr/include/bits/types.h
filterchains.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
filterchains.o: /usr/include/libio.h /usr/include/_G_config.h
filterchains.o: /usr/include/wchar.h /usr/include/bits/wchar.h
filterchains.o: /usr/include/gconv.h
filterchains.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
filterchains.o: /usr/include/bits/stdio_lim.h /usr/include/arpa/inet.h
filterchains.o: /usr/include/netinet/in.h /usr/include/stdint.h
filterchains.o: /usr/include/bits/wordsize.h /usr/include/bits/socket.h
filterchains.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
filterchains.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
filterchains.o: /usr/include/bits/posix2_lim.h /usr/include/sys/types.h
filterchains.o: /usr/include/time.h /usr/include/endian.h
filterchains.o: /usr/include/bits/endian.h /usr/include/sys/select.h
filterchains.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
filterchains.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
filterchains.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
filterchains.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
filterchains.o: /usr/include/bits/byteswap.h /usr/include/syslog.h
filterchains.o: /usr/include/sys/syslog.h filterchains.h varlist.h
filterchains.o: filterchains2.h ./iptables/include/iptables.h
filterchains.o: ./iptables/include/iptables_common.h
filterchains.o: ./iptables/include/libiptc/libiptc.h
filterchains.o: ./iptables/include/libiptc/ipt_kernel_headers.h
filterchains.o: /usr/include/netinet/ip.h /usr/include/netinet/ip_icmp.h
filterchains.o: /usr/include/netinet/tcp.h /usr/include/netinet/udp.h
filterchains.o: /usr/include/net/if.h /usr/include/sys/socket.h
filterchains.o: /usr/include/sys/uio.h /usr/include/bits/uio.h
filterchains.o: /usr/include/linux/netfilter_ipv4/ip_tables.h
filterchains.o: /usr/include/linux/netfilter_ipv4.h
filterchains.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
filterchains.o: /usr/include/linux/netfilter.h
filterchains2.o: /usr/include/string.h /usr/include/features.h
filterchains2.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
filterchains2.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
filterchains2.o: /usr/include/netdb.h /usr/include/netinet/in.h
filterchains2.o: /usr/include/stdint.h /usr/include/bits/wchar.h
filterchains2.o: /usr/include/bits/wordsize.h /usr/include/bits/types.h
filterchains2.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
filterchains2.o: /usr/include/bits/socket.h /usr/include/limits.h
filterchains2.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
filterchains2.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
filterchains2.o: /usr/include/sys/types.h /usr/include/time.h
filterchains2.o: /usr/include/endian.h /usr/include/bits/endian.h
filterchains2.o: /usr/include/sys/select.h /usr/include/bits/select.h
filterchains2.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
filterchains2.o: /usr/include/sys/sysmacros.h /usr/include/bits/sockaddr.h
filterchains2.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
filterchains2.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
filterchains2.o: /usr/include/rpc/netdb.h /usr/include/bits/netdb.h
filterchains2.o: /usr/include/errno.h /usr/include/bits/errno.h
filterchains2.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
filterchains2.o: /usr/include/stdio.h /usr/include/libio.h
filterchains2.o: /usr/include/_G_config.h /usr/include/wchar.h
filterchains2.o: /usr/include/gconv.h
filterchains2.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
filterchains2.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
filterchains2.o: /usr/include/alloca.h /usr/include/dlfcn.h
filterchains2.o: /usr/include/bits/dlfcn.h /usr/include/ctype.h
filterchains2.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
filterchains2.o: /usr/include/bits/confname.h /usr/include/getopt.h
filterchains2.o: ./iptables/include/iptables.h
filterchains2.o: ./iptables/include/iptables_common.h
filterchains2.o: ./iptables/include/libiptc/libiptc.h
filterchains2.o: ./iptables/include/libiptc/ipt_kernel_headers.h
filterchains2.o: /usr/include/netinet/ip.h /usr/include/netinet/ip_icmp.h
filterchains2.o: /usr/include/netinet/tcp.h /usr/include/netinet/udp.h
filterchains2.o: /usr/include/net/if.h /usr/include/sys/socket.h
filterchains2.o: /usr/include/sys/uio.h /usr/include/bits/uio.h
filterchains2.o: /usr/include/linux/netfilter_ipv4/ip_tables.h
filterchains2.o: /usr/include/linux/netfilter_ipv4.h
filterchains2.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
filterchains2.o: /usr/include/linux/netfilter.h /usr/include/fcntl.h
filterchains2.o: /usr/include/bits/fcntl.h /usr/include/sys/wait.h
filterchains2.o: /usr/include/signal.h /usr/include/bits/signum.h
filterchains2.o: /usr/include/bits/siginfo.h /usr/include/bits/sigaction.h
filterchains2.o: /usr/include/bits/sigcontext.h /usr/include/asm/sigcontext.h
filterchains2.o: /usr/include/bits/sigstack.h /usr/include/bits/sigthread.h
filterchains2.o: /usr/include/sys/resource.h /usr/include/bits/resource.h
filterchains2.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
filterchains2.o: /usr/include/arpa/inet.h /usr/include/syslog.h
filterchains2.o: /usr/include/sys/syslog.h
commands.o: /usr/include/syslog.h /usr/include/sys/syslog.h
commands.o: /usr/include/features.h /usr/include/sys/cdefs.h
commands.o: /usr/include/gnu/stubs.h
commands.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
commands.o: /usr/include/stdio.h
commands.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
commands.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
commands.o: /usr/include/bits/sched.h /usr/include/libio.h
commands.o: /usr/include/_G_config.h /usr/include/wchar.h
commands.o: /usr/include/bits/wchar.h /usr/include/gconv.h
commands.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
commands.o: /usr/include/sys/types.h /usr/include/time.h
commands.o: /usr/include/endian.h /usr/include/bits/endian.h
commands.o: /usr/include/sys/select.h /usr/include/bits/select.h
commands.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
commands.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
commands.o: /usr/include/string.h /usr/include/unistd.h
commands.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
commands.o: /usr/include/getopt.h /usr/include/errno.h
commands.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
commands.o: /usr/include/asm/errno.h /usr/include/netinet/in.h
commands.o: /usr/include/stdint.h /usr/include/bits/wordsize.h
commands.o: /usr/include/bits/socket.h /usr/include/limits.h
commands.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
commands.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
commands.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
commands.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
commands.o: /usr/include/bits/byteswap.h /usr/include/arpa/inet.h varlist.h
commands.o: usernode.h /usr/include/linux/if_arp.h
commands.o: /usr/include/linux/netdevice.h /usr/include/linux/if.h
commands.o: /usr/include/linux/types.h /usr/include/linux/posix_types.h
commands.o: /usr/include/linux/stddef.h /usr/include/asm/posix_types.h
commands.o: /usr/include/asm/types.h /usr/include/linux/socket.h
commands.o: /usr/include/linux/if_ether.h /usr/include/linux/if_packet.h
commands.o: /usr/include/asm/atomic.h /usr/include/linux/config.h
commands.o: /usr/include/linux/autoconf.h /usr/include/asm/cache.h
commands.o: /usr/include/asm/byteorder.h
commands.o: /usr/include/linux/byteorder/little_endian.h
commands.o: /usr/include/linux/byteorder/swab.h
commands.o: /usr/include/linux/byteorder/generic.h filterchains.h hlcrypt.h
commands.o: /usr/include/openssl/sha.h /usr/include/crypt.h find_interface.h
commands.o: conffile.h misc.h config.h mymalloc.h accounting.h
icmpping.o: /usr/include/netinet/ip.h /usr/include/features.h
icmpping.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
icmpping.o: /usr/include/sys/types.h /usr/include/bits/types.h
icmpping.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
icmpping.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
icmpping.o: /usr/include/time.h /usr/include/endian.h
icmpping.o: /usr/include/bits/endian.h /usr/include/sys/select.h
icmpping.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
icmpping.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
icmpping.o: /usr/include/netinet/in.h /usr/include/stdint.h
icmpping.o: /usr/include/bits/wchar.h /usr/include/bits/wordsize.h
icmpping.o: /usr/include/bits/socket.h /usr/include/limits.h
icmpping.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
icmpping.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
icmpping.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
icmpping.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
icmpping.o: /usr/include/bits/byteswap.h /usr/include/netinet/ip_icmp.h
icmpping.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
icmpping.o: /usr/include/bits/uio.h /usr/include/syslog.h
icmpping.o: /usr/include/sys/syslog.h
icmpping.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
icmpping.o: /usr/include/errno.h /usr/include/bits/errno.h
icmpping.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
icmpping.o: /usr/include/stdlib.h /usr/include/alloca.h /usr/include/stdio.h
icmpping.o: /usr/include/libio.h /usr/include/_G_config.h
icmpping.o: /usr/include/wchar.h /usr/include/gconv.h
icmpping.o: /usr/include/bits/stdio_lim.h /usr/include/arpa/inet.h
icmpping.o: /usr/include/string.h socketnode.h usernode.h
icmpping.o: /usr/include/linux/if_arp.h /usr/include/linux/netdevice.h
icmpping.o: /usr/include/linux/if.h /usr/include/linux/types.h
icmpping.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
icmpping.o: /usr/include/asm/posix_types.h /usr/include/asm/types.h
icmpping.o: /usr/include/linux/socket.h /usr/include/linux/if_ether.h
icmpping.o: /usr/include/linux/if_packet.h /usr/include/asm/atomic.h
icmpping.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
icmpping.o: /usr/include/asm/cache.h /usr/include/asm/byteorder.h
icmpping.o: /usr/include/linux/byteorder/little_endian.h
icmpping.o: /usr/include/linux/byteorder/swab.h
icmpping.o: /usr/include/linux/byteorder/generic.h varlist.h mymalloc.h
icmpping.o: trace.h
arpping.o: /usr/include/syslog.h /usr/include/sys/syslog.h
arpping.o: /usr/include/features.h /usr/include/sys/cdefs.h
arpping.o: /usr/include/gnu/stubs.h
arpping.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
arpping.o: /usr/include/stdlib.h
arpping.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
arpping.o: /usr/include/sys/types.h /usr/include/bits/types.h
arpping.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
arpping.o: /usr/include/time.h /usr/include/endian.h
arpping.o: /usr/include/bits/endian.h /usr/include/sys/select.h
arpping.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
arpping.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
arpping.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/libio.h
arpping.o: /usr/include/_G_config.h /usr/include/wchar.h
arpping.o: /usr/include/bits/wchar.h /usr/include/gconv.h
arpping.o: /usr/include/bits/stdio_lim.h /usr/include/sys/time.h
arpping.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
arpping.o: /usr/include/bits/uio.h /usr/include/bits/socket.h
arpping.o: /usr/include/limits.h /usr/include/bits/wordsize.h
arpping.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
arpping.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
arpping.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
arpping.o: /usr/include/asm/sockios.h /usr/include/netinet/in.h
arpping.o: /usr/include/stdint.h /usr/include/bits/in.h
arpping.o: /usr/include/bits/byteswap.h /usr/include/linux/sockios.h
arpping.o: /usr/include/linux/if.h /usr/include/linux/types.h
arpping.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
arpping.o: /usr/include/asm/posix_types.h /usr/include/asm/types.h
arpping.o: /usr/include/linux/socket.h /usr/include/linux/if_arp.h
arpping.o: /usr/include/linux/netdevice.h /usr/include/linux/if_ether.h
arpping.o: /usr/include/linux/if_packet.h /usr/include/asm/atomic.h
arpping.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
arpping.o: /usr/include/asm/cache.h /usr/include/asm/byteorder.h
arpping.o: /usr/include/linux/byteorder/little_endian.h
arpping.o: /usr/include/linux/byteorder/swab.h
arpping.o: /usr/include/linux/byteorder/generic.h /usr/include/arpa/inet.h
arpping.o: /usr/include/string.h usernode.h varlist.h socketnode.h mymalloc.h
arpping.o: trace.h
config.o: /usr/include/stdio.h /usr/include/features.h
config.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
config.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
config.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
config.o: /usr/include/bits/sched.h /usr/include/libio.h
config.o: /usr/include/_G_config.h /usr/include/wchar.h
config.o: /usr/include/bits/wchar.h /usr/include/gconv.h
config.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
config.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
config.o: /usr/include/arpa/inet.h /usr/include/netinet/in.h
config.o: /usr/include/stdint.h /usr/include/bits/wordsize.h
config.o: /usr/include/bits/socket.h /usr/include/limits.h
config.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
config.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
config.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
config.o: /usr/include/bits/endian.h /usr/include/sys/select.h
config.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
config.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
config.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
config.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
config.o: /usr/include/bits/byteswap.h config.h
ilglue.o: /usr/include/stdio.h /usr/include/features.h
ilglue.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ilglue.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
ilglue.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
ilglue.o: /usr/include/bits/sched.h /usr/include/libio.h
ilglue.o: /usr/include/_G_config.h /usr/include/wchar.h
ilglue.o: /usr/include/bits/wchar.h /usr/include/gconv.h
ilglue.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
ilglue.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
ilglue.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
ilglue.o: /usr/include/bits/endian.h /usr/include/sys/select.h
ilglue.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
ilglue.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
ilglue.o: /usr/include/alloca.h /usr/include/unistd.h
ilglue.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
ilglue.o: /usr/include/getopt.h /usr/include/string.h
ilglue.o: /usr/include/netinet/in.h /usr/include/stdint.h
ilglue.o: /usr/include/bits/wordsize.h /usr/include/bits/socket.h
ilglue.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
ilglue.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
ilglue.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
ilglue.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
ilglue.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
ilglue.o: /usr/include/netdb.h /usr/include/rpc/netdb.h
ilglue.o: /usr/include/bits/netdb.h /usr/include/errno.h
ilglue.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
ilglue.o: /usr/include/asm/errno.h /usr/include/syslog.h
ilglue.o: /usr/include/sys/syslog.h /usr/include/arpa/inet.h
ilglue.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
ilglue.o: /usr/include/bits/uio.h conffile.h varlist.h hlcrypt.h
ilglue.o: /usr/include/openssl/sha.h /usr/include/crypt.h misc.h config.h
misc.o: /usr/include/stdlib.h /usr/include/features.h
misc.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
misc.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
misc.o: /usr/include/sys/types.h /usr/include/bits/types.h
misc.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
misc.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
misc.o: /usr/include/sys/select.h /usr/include/bits/select.h
misc.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
misc.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
misc.o: /usr/include/arpa/inet.h /usr/include/netinet/in.h
misc.o: /usr/include/stdint.h /usr/include/bits/wchar.h
misc.o: /usr/include/bits/wordsize.h /usr/include/bits/socket.h
misc.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
misc.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
misc.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
misc.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
misc.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
misc.o: /usr/include/sys/wait.h /usr/include/signal.h
misc.o: /usr/include/bits/signum.h /usr/include/bits/siginfo.h
misc.o: /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h
misc.o: /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h
misc.o: /usr/include/bits/sigthread.h /usr/include/sys/resource.h
misc.o: /usr/include/bits/resource.h /usr/include/bits/waitflags.h
misc.o: /usr/include/bits/waitstatus.h /usr/include/sys/socket.h
misc.o: /usr/include/sys/uio.h /usr/include/bits/uio.h /usr/include/unistd.h
misc.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
misc.o: /usr/include/getopt.h /usr/include/netdb.h /usr/include/rpc/netdb.h
misc.o: /usr/include/bits/netdb.h /usr/include/stdio.h /usr/include/libio.h
misc.o: /usr/include/_G_config.h /usr/include/wchar.h /usr/include/gconv.h
misc.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
misc.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
misc.o: /usr/include/syslog.h /usr/include/sys/syslog.h config.h
usernode.o: /usr/include/stdlib.h /usr/include/features.h
usernode.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
usernode.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
usernode.o: /usr/include/sys/types.h /usr/include/bits/types.h
usernode.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
usernode.o: /usr/include/time.h /usr/include/endian.h
usernode.o: /usr/include/bits/endian.h /usr/include/sys/select.h
usernode.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
usernode.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
usernode.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/libio.h
usernode.o: /usr/include/_G_config.h /usr/include/wchar.h
usernode.o: /usr/include/bits/wchar.h /usr/include/gconv.h
usernode.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
usernode.o: /usr/include/bits/stdio_lim.h /usr/include/syslog.h
usernode.o: /usr/include/sys/syslog.h /usr/include/string.h
usernode.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
usernode.o: /usr/include/bits/confname.h /usr/include/getopt.h
usernode.o: /usr/include/arpa/inet.h /usr/include/netinet/in.h
usernode.o: /usr/include/stdint.h /usr/include/bits/wordsize.h
usernode.o: /usr/include/bits/socket.h /usr/include/limits.h
usernode.o: /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h
usernode.o: /usr/include/linux/limits.h /usr/include/bits/posix2_lim.h
usernode.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
usernode.o: /usr/include/asm/sockios.h /usr/include/bits/in.h
usernode.o: /usr/include/bits/byteswap.h /usr/include/sys/timeb.h usernode.h
usernode.o: /usr/include/linux/if_arp.h /usr/include/linux/netdevice.h
usernode.o: /usr/include/linux/if.h /usr/include/linux/types.h
usernode.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
usernode.o: /usr/include/asm/posix_types.h /usr/include/asm/types.h
usernode.o: /usr/include/linux/socket.h /usr/include/linux/if_ether.h
usernode.o: /usr/include/linux/if_packet.h /usr/include/asm/atomic.h
usernode.o: /usr/include/linux/config.h /usr/include/linux/autoconf.h
usernode.o: /usr/include/asm/cache.h /usr/include/asm/byteorder.h
usernode.o: /usr/include/linux/byteorder/little_endian.h
usernode.o: /usr/include/linux/byteorder/swab.h
usernode.o: /usr/include/linux/byteorder/generic.h varlist.h accounting.h
varlist.o: /usr/include/string.h /usr/include/features.h
varlist.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
varlist.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
varlist.o: /usr/include/stdlib.h /usr/include/sys/types.h
varlist.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
varlist.o: /usr/include/bits/sched.h /usr/include/time.h
varlist.o: /usr/include/endian.h /usr/include/bits/endian.h
varlist.o: /usr/include/sys/select.h /usr/include/bits/select.h
varlist.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
varlist.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
varlist.o: /usr/include/ctype.h varlist.h
hlcrypt.o: /usr/include/stdio.h /usr/include/features.h
hlcrypt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
hlcrypt.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
hlcrypt.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
hlcrypt.o: /usr/include/bits/sched.h /usr/include/libio.h
hlcrypt.o: /usr/include/_G_config.h /usr/include/wchar.h
hlcrypt.o: /usr/include/bits/wchar.h /usr/include/gconv.h
hlcrypt.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
hlcrypt.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
hlcrypt.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/endian.h
hlcrypt.o: /usr/include/bits/endian.h /usr/include/sys/select.h
hlcrypt.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
hlcrypt.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
hlcrypt.o: /usr/include/alloca.h /usr/include/string.h /usr/include/syslog.h
hlcrypt.o: /usr/include/sys/syslog.h /usr/include/sys/time.h
hlcrypt.o: /usr/include/errno.h /usr/include/bits/errno.h
hlcrypt.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
hlcrypt.o: /usr/include/sys/stat.h /usr/include/bits/stat.h
hlcrypt.o: /usr/include/netinet/in.h /usr/include/stdint.h
hlcrypt.o: /usr/include/bits/wordsize.h /usr/include/bits/socket.h
hlcrypt.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
hlcrypt.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
hlcrypt.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
hlcrypt.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
hlcrypt.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
hlcrypt.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
hlcrypt.o: /usr/include/bits/confname.h /usr/include/getopt.h hlcrypt.h
hlcrypt.o: /usr/include/openssl/sha.h /usr/include/crypt.h
conffile.o: /usr/include/stdio.h /usr/include/features.h
conffile.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
conffile.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
conffile.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
conffile.o: /usr/include/bits/sched.h /usr/include/libio.h
conffile.o: /usr/include/_G_config.h /usr/include/wchar.h
conffile.o: /usr/include/bits/wchar.h /usr/include/gconv.h
conffile.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
conffile.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
conffile.o: /usr/include/stdlib.h /usr/include/sys/types.h
conffile.o: /usr/include/time.h /usr/include/endian.h
conffile.o: /usr/include/bits/endian.h /usr/include/sys/select.h
conffile.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
conffile.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
conffile.o: /usr/include/alloca.h /usr/include/ctype.h /usr/include/unistd.h
conffile.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
conffile.o: /usr/include/getopt.h conffile.h varlist.h
trace.o: /usr/include/stdio.h /usr/include/features.h
trace.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
trace.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
trace.o: /usr/include/bits/types.h /usr/include/bits/pthreadtypes.h
trace.o: /usr/include/bits/sched.h /usr/include/libio.h
trace.o: /usr/include/_G_config.h /usr/include/wchar.h
trace.o: /usr/include/bits/wchar.h /usr/include/gconv.h
trace.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
trace.o: /usr/include/bits/stdio_lim.h /usr/include/sys/timeb.h
trace.o: /usr/include/time.h conffile.h varlist.h
mymalloc.o: /usr/include/stdlib.h /usr/include/features.h
mymalloc.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
mymalloc.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stddef.h
mymalloc.o: /usr/include/sys/types.h /usr/include/bits/types.h
mymalloc.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
mymalloc.o: /usr/include/time.h /usr/include/endian.h
mymalloc.o: /usr/include/bits/endian.h /usr/include/sys/select.h
mymalloc.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
mymalloc.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
mymalloc.o: /usr/include/alloca.h /usr/include/stdio.h /usr/include/libio.h
mymalloc.o: /usr/include/_G_config.h /usr/include/wchar.h
mymalloc.o: /usr/include/bits/wchar.h /usr/include/gconv.h
mymalloc.o: /usr/lib/gcc-lib/i386-slackware-linux/2.95.2/include/stdarg.h
mymalloc.o: /usr/include/bits/stdio_lim.h /usr/include/syslog.h
mymalloc.o: /usr/include/sys/syslog.h
